env:
  browser: true
  es2021: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
rules: {
  '@typescript-eslint/no-confusing-void-expression': 'off',
  "@typescript-eslint/ban-types": [
    "error",
    {
      "extendDefaults": true,
      "types": {
        "{}": false
      }
    }
  ]
}
